import type { Exercise } from "@/types";
import type { StaticClipId } from "@/lib/staticAudio";

/**
 * Maps exercise id -> pre-generated instruction audio URL (Section 5c).
 * GENERATED by scripts/generate-audio.ts — do not edit by hand. Empty until
 * audio is generated, in which case the player falls back to the Web Speech API.
 */
export const EXERCISE_AUDIO: Record<string, string> = {
  "seated_band_row": "/audio/seated_band_row.wav",
  "seated_lateral_raise": "/audio/seated_lateral_raise.wav",
  "lying_knee_to_chest": "/audio/lying_knee_to_chest.wav",
  "seated_march": "/audio/seated_march.wav",
  "wall_pushup": "/audio/wall_pushup.wav",
  "seated_torso_twist": "/audio/seated_torso_twist.wav",
  "lying_band_chest_press": "/audio/lying_band_chest_press.wav",
  "seated_ankle_circles": "/audio/seated_ankle_circles.wav",
  "seated_shoulder_shrugs": "/audio/seated_shoulder_shrugs.wav",
  "seated_neck_stretch": "/audio/seated_neck_stretch.wav",
  "seated_arm_circles": "/audio/seated_arm_circles.wav",
  "seated_wrist_rolls": "/audio/seated_wrist_rolls.wav",
  "seated_bicep_curl": "/audio/seated_bicep_curl.wav",
  "seated_overhead_press": "/audio/seated_overhead_press.wav",
  "seated_band_pull_apart": "/audio/seated_band_pull_apart.wav",
  "seated_band_chest_press": "/audio/seated_band_chest_press.wav",
  "seated_band_overhead_pull": "/audio/seated_band_overhead_pull.wav",
  "seated_side_bend": "/audio/seated_side_bend.wav",
  "seated_boxer_punches": "/audio/seated_boxer_punches.wav",
  "seated_knee_extension": "/audio/seated_knee_extension.wav",
  "seated_heel_raises": "/audio/seated_heel_raises.wav",
  "seated_forward_fold": "/audio/seated_forward_fold.wav",
  "seated_band_shoulder_rotation": "/audio/seated_band_shoulder_rotation.wav",
  "lying_side_leg_lift": "/audio/lying_side_leg_lift.wav",
  "lying_arm_reach_cross": "/audio/lying_arm_reach_cross.wav",
  "lying_band_leg_press": "/audio/lying_band_leg_press.wav",
  "lying_pelvic_tilt": "/audio/lying_pelvic_tilt.wav",
  "lying_chest_opener": "/audio/lying_chest_opener.wav",
  "lying_heel_slides": "/audio/lying_heel_slides.wav",
  "standing_chair_squat": "/audio/standing_chair_squat.wav",
  "standing_wall_lean_calf": "/audio/standing_wall_lean_calf.wav",
  "standing_side_leg_raise": "/audio/standing_side_leg_raise.wav",
  "standing_march": "/audio/standing_march.wav",
  "standing_wall_slide": "/audio/standing_wall_slide.wav",
  "seated_deep_breathing": "/audio/seated_deep_breathing.wav",
  "seated_arm_raise": "/audio/seated_arm_raise.wav",
  "isometric_glute_contraction": "/audio/isometric_glute_contraction.wav",
  "wheelchair_pushups": "/audio/wheelchair_pushups.wav",
  "seated_adaptive_yoga": "/audio/seated_adaptive_yoga.wav",
};

/**
 * Maps static-clip id (rest cue, etc.) -> pre-generated audio URL (Section 5c).
 * GENERATED by scripts/generate-audio.ts — do not edit by hand. Empty until
 * audio is generated, in which case the player falls back to the Web Speech API.
 */
export const STATIC_AUDIO: Partial<Record<StaticClipId, string>> = {
  "rest": "/audio/rest.wav",
  "calibrate_seated_arm_raise": "/audio/calibrate_seated_arm_raise.wav",
  "calibrate_seated_bicep_curl": "/audio/calibrate_seated_bicep_curl.wav",
};

/** The instruction-audio URL for an exercise, or null to use Web Speech.
 * Prefers the seed's `audio_url`, then the generated manifest. */
export function getExerciseAudioUrl(
  exercise: Pick<Exercise, "id" | "audio_url">,
): string | null {
  return exercise.audio_url ?? EXERCISE_AUDIO[exercise.id] ?? null;
}

/** The pre-generated URL for a static clip (e.g. the rest cue), or null to use
 * Web Speech. */
export function getStaticAudioUrl(id: StaticClipId): string | null {
  return STATIC_AUDIO[id] ?? null;
}
